spring.application.name=comic-info-service
server.port=8082
eureka.instance.prefer-ip-address=true

# tells Spring where the database/source is (check SPRING_DATAxxx else fallback)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/comic_info_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:comic_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:comic_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false